# Generated by Django 3.0.5 on 2020-04-08 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appsettings',
            fields=[
                ('key', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('value', models.CharField(blank=True, default='', max_length=128)),
            ],
        ),
    ]
